groups:
  - name: error-rules
    rules:
    - alert: HighErrorRate
      expr: (sum(rate(error_counts[5m])) / (sum(rate(request_counts[5m]))) > 0.1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "High error rate: {{ $value }}"