# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "monitor-app-infra"
    encrypt = true
    key     = "ecs/cluster/terraform.tfstate"
    profile = "ersel-local"
    region  = "eu-central-1"
  }
}
